name: Notify Webhook

on:
    push:
        branches:
            - main

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Install requests
              run: pip install requests
            - name: Notify TeamRoom Webhook
              run: |
                  python notify_webhook.py
